name: Documentation
description: Documentation-only changes (no code changes)
labels: ["docs"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What documentation needs to change and why?
    validations:
      required: true
  - type: textarea
    id: affected-docs
    attributes:
      label: Affected Documents
      description: Which files need updating?
      placeholder: |
        - docs/functional-spec.md — Section X
        - CLAUDE.md — File Structure section
        - README.md — Features list
  - type: textarea
    id: done
    attributes:
      label: Definition of Done
      value: |
        - [ ] Documentation updated
        - [ ] Content is accurate and matches current code
        - [ ] No broken links or references
        - [ ] Consistent across all affected documents
